repos:
  - repo: local
    hooks:
      - id: local-integration-tests
        name: Run local integration tests
        entry: ./api/scripts/integration_test.sh
        language: script
        pass_filenames: false
