name: Docker Build and Push

on:
  push:
    paths:
      - "frontend/**"
  # - "api/**"
  # push:
  # branches:
  # - main

jobs:
  docker-frontend:
    runs-on: ubuntu-latest
    # if: contains(github.event.head_commit.message, 'build-frontend') || contains(github.event.commits[0].modified, 'frontend')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image for Frontend
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: ghcr.io/${{ github.repository }}/frontend:latest
